image: 'lupusanay/rust-diesel:latest'

stages:
  - test
  - doc
  - build
  - deploy

variables:
  POSTGRES_DB: blog
  POSTGRES_USER: lupusanay
  POSTGRES_PASSWORD: qwerty
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

services:
  - postgres:latest

before_script:
  - .cargo/bin/diesel migration run

test:
  stage: test
  variables:
    DATABASE_URL: postgres://lupusanay:qwerty@postgres/blog
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

production:
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lupusanay-blog-rust --api-key=$HEROKU_PRODUCTION_API_KEY

cache:
  paths:
    - apt/
    - .cargo/
    - target/