image: 'lupusanay/rust-diesel:latest'

stages:
  - test
  - doc
  - build
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

test:
  services:
    - postgres:latest
  stage: test
  variables:
    POSTGRES_DB: blog
    POSTGRES_USER: lupusanay
    POSTGRES_PASSWORD: qwerty
    DATABASE_URL: postgres://lupusanay:qwerty@postgres/blog
  script:
    - diesel migration run
    - rustc --version
    - cargo --version
    - cargo test --verbose

production:
  stage: deploy
  script:
    - cd static/
    - npm install --progress=false
    - npm run build
    - dpl --provider=heroku --app=lupusanay-blog-rust --api-key=$HEROKU_PRODUCTION_API_KEY --skip_cleanup
  artifacts:
    paths:
      - static/dist/

cache:
  paths:
    - apt/
    - cargo/
    - target/