image: 'rustlang/rust:nightly'

stages:
  - test
  - doc
  - build

variables:
  POSTGRES_DB: blog
  POSTGRES_USER: lupusanay
  POSTGRES_PASSWORD: qwerty
  DATABASE_URL: postgres://lupusanay:qwerty@postgres/blog
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

services:
  - postgres:latest

before_script:
  - apt-get update -yq
  - apt-get install -y postgresql-client libpq-dev
  - rustup override set nightly

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose


cache:
  paths:
    - apt/
    - cargo/
    - target/