image: 'lupusanay/rust-diesel:latest'

stages:
  - test
  - doc
  - build
  - deploy

variables:
  POSTGRES_DB: blog
  POSTGRES_USER: lupusanay
  POSTGRES_PASSWORD: qwerty
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

services:
  - postgres:latest

test:
  stage: test
  variables:
    DATABASE_URL: postgres://lupusanay:qwerty@postgres/blog
  script:
    - diesel migration run
    - rustc --version
    - cargo --version
    - cargo test --verbose

build:
  stage: build
  image: node:latest
  script:
    - cd static/
    - npm install --progress=false
    - npm run build
  artifacts:
    paths:
      - static/dist/

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=lupusanay-blog-rust --api-key=$HEROKU_PRODUCTION_API_KEY --skip_cleanup

cache:
  paths:
    - apt/
    - cargo/
    - target/